"""
JSON Schema to GBNF Grammar Compiler and Structured Token Constrainer.
Zero external dependencies, standard library only.
"""

from typing import Dict, List, Any, Optional

class JSONSchemaGrammarCompilerClient:
    """
    Translates JSON Schema / Pydantic object schemas into Context-Free
    GBNF (GGML BNF) grammar rules enforcing valid JSON token generation.
    """

    def __init__(self):
        pass

    def compile_schema_to_gbnf(self, schema: Dict[str, Any], root_rule: str = "root") -> str:
        """
        Compiles JSON schema dictionary into GBNF grammar specification.
        """
        rules = []
        rules.append("# GBNF Grammar Generated by GenPark AI")
        rules.append('ws ::= [ \t\n]*')
        rules.append('string ::= "\"" ([^"\\\r\n] | "\\" (["\\/bfnrt] | "u" [0-9a-fA-F] [0-9a-fA-F] [0-9a-fA-F] [0-9a-fA-F]))* "\""')
        rules.append('number ::= ("-"? ([0-9] | [1-9] [0-9]*)) ("." [0-9]+)? ([eE] [-+]? [0-9]+)?')
        rules.append('boolean ::= "true" | "false"')
        rules.append('null ::= "null"')

        schema_type = schema.get("type", "object")
        if schema_type == "object":
            props = schema.get("properties", {})
            required = schema.get("required", list(props.keys()))

            obj_subrules = []
            for prop_name, prop_def in props.items():
                p_type = prop_def.get("type", "string")
                rule_name = f"{root_rule}_{prop_name}_prop"
                
                if p_type == "string":
                    val_rule = "string"
                elif p_type in ("integer", "number"):
                    val_rule = "number"
                elif p_type == "boolean":
                    val_rule = "boolean"
                elif p_type == "array":
                    val_rule = f'"[" ws ({root_rule}_{prop_name}_item (ws "," ws {root_rule}_{prop_name}_item)*)? ws "]"'
                    rules.append(f"{root_rule}_{prop_name}_item ::= string")
                else:
                    val_rule = "string"

                rules.append(f'{rule_name} ::= "\"" "{prop_name}" "\"" ws ":" ws {val_rule}')
                obj_subrules.append(rule_name)

            # Object construction
            prop_chain = ' ws "," ws '.join(obj_subrules)
            rules.append(f'{root_rule} ::= "{{" ws {prop_chain} ws "}}"')
        else:
            rules.append(f'{root_rule} ::= string')

        return "
".join(rules)

    def validate_payload_against_schema(self, payload: Dict[str, Any], schema: Dict[str, Any]) -> Dict[str, Any]:
        """Verifies whether dictionary conforms to schema specifications."""
        errors = []
        req_props = schema.get("required", [])
        for req in req_props:
            if req not in payload:
                errors.append(f"Missing required property: '{req}'")

        props = schema.get("properties", {})
        for k, v in payload.items():
            if k in props:
                expected_type = props[k].get("type")
                if expected_type == "string" and not isinstance(v, str):
                    errors.append(f"Property '{k}' expected string, got {type(v).__name__}")
                elif expected_type == "integer" and not isinstance(v, int):
                    errors.append(f"Property '{k}' expected int, got {type(v).__name__}")
                elif expected_type == "boolean" and not isinstance(v, bool):
                    errors.append(f"Property '{k}' expected bool, got {type(v).__name__}")
                elif expected_type == "number" and not isinstance(v, (int, float)):
                    errors.append(f"Property '{k}' expected number, got {type(v).__name__}")

        return {
            "valid": len(errors) == 0,
            "errors": errors
        }
